export const  goverments=[
     { name: 'القاهرة', selected: false },
    { name: 'الجيزة', selected: false },
    { name: 'الإسكندرية', selected: false },
    { name: 'الشرقية', selected: false },
    { name: 'الدقهلية', selected: false },
    { name: 'الغربية', selected: false },
    { name: 'المنوفية', selected: false },
    { name: 'القليوبية', selected: false },
    { name: 'البحيرة', selected: false },
    { name: 'كفر الشيخ', selected: false },
    { name: 'الفيوم', selected: false },
    { name: 'بني سويف', selected: false },
    { name: 'المنيا', selected: false },
    { name: 'أسيوط', selected: false },
    { name: 'سوهاج', selected: false },
    { name: 'قنا', selected: false },
    { name: 'الأقصر', selected: false },
    { name: 'أسوان', selected: false },
    { name: 'الإسماعيلية', selected: false },
    { name: 'السويس', selected: false },
    { name: 'بورسعيد', selected: false },
    { name: 'دمياط', selected: false },
]